global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - '10.0.2.10:9100'
          - '10.0.3.10:9100'
          - '10.0.1.10:9100'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - '10.0.2.10:8080'
          - '10.0.3.10:8080'
          - '10.0.1.10:8080'

  - job_name: 'open5gs'
    fallback_scrape_protocol: PrometheusText0.0.4
    static_configs:
      - targets:
          - 'amf:9090'
          - 'smf:9090'
          - 'pcf:9090'
