services:
  mongodb:
    image: mongo:6
    networks:
      - overlay-5g
    volumes:
      - mongodb-data:/data/db
    deploy:
      placement:
        constraints:
          - node.hostname == vm-core-5g

  nrf:
    image: gradiant/open5gs:2.7.0
    entrypoint: [""]
    command: ["bash", "-c", "mkdir -p /var/log/open5gs && open5gs-nrfd"]
    volumes:
      - /home/ubuntu/config/open5gs:/opt/open5gs/etc/open5gs
    networks:
      - overlay-5g
    deploy:
      placement:
        constraints:
          - node.hostname == vm-core-5g

  ausf:
    image: gradiant/open5gs:2.7.0
    entrypoint: [""]
    command: ["bash", "-c", "mkdir -p /var/log/open5gs && sleep 5 && open5gs-ausfd"]
    volumes:
      - /home/ubuntu/config/open5gs:/opt/open5gs/etc/open5gs
    networks:
      - overlay-5g
    deploy:
      placement:
        constraints:
          - node.hostname == vm-core-5g

  udm:
    image: gradiant/open5gs:2.7.0
    entrypoint: [""]
    command: ["bash", "-c", "mkdir -p /var/log/open5gs && sleep 5 && open5gs-udmd"]
    volumes:
      - /home/ubuntu/config/open5gs:/opt/open5gs/etc/open5gs
    networks:
      - overlay-5g
    deploy:
      placement:
        constraints:
          - node.hostname == vm-core-5g

  udr:
    image: gradiant/open5gs:2.7.0
    entrypoint: [""]
    command: ["bash", "-c", "mkdir -p /var/log/open5gs && sleep 5 && open5gs-udrd"]
    volumes:
      - /home/ubuntu/config/open5gs:/opt/open5gs/etc/open5gs
    environment:
      - DB_URI=mongodb://mongodb/open5gs
    networks:
      - overlay-5g
    deploy:
      placement:
        constraints:
          - node.hostname == vm-core-5g

  pcf:
    image: gradiant/open5gs:2.7.0
    entrypoint: [""]
    command: ["bash", "-c", "mkdir -p /var/log/open5gs && sleep 5 && open5gs-pcfd"]
    volumes:
      - /home/ubuntu/config/open5gs:/opt/open5gs/etc/open5gs
    environment:
      - DB_URI=mongodb://mongodb/open5gs
    networks:
      - overlay-5g
    deploy:
      placement:
        constraints:
          - node.hostname == vm-core-5g

  bsf:
    image: gradiant/open5gs:2.7.0
    entrypoint: [""]
    command: ["bash", "-c", "mkdir -p /var/log/open5gs && sleep 5 && open5gs-bsfd"]
    volumes:
      - /home/ubuntu/config/open5gs:/opt/open5gs/etc/open5gs
    networks:
      - overlay-5g
    deploy:
      placement:
        constraints:
          - node.hostname == vm-core-5g

  smf:
    image: gradiant/open5gs:2.7.0
    entrypoint: [""]
    command: ["bash", "-c", "mkdir -p /var/log/open5gs && sleep 10 && open5gs-smfd"]
    volumes:
      - /home/ubuntu/config/open5gs:/opt/open5gs/etc/open5gs
    networks:
      - overlay-5g
    deploy:
      placement:
        constraints:
          - node.hostname == vm-core-5g

  amf:
    image: gradiant/open5gs:2.7.0
    entrypoint: [""]
    command: ["bash", "-c", "mkdir -p /var/log/open5gs && sleep 15 && open5gs-amfd"]
    volumes:
      - /home/ubuntu/config/open5gs:/opt/open5gs/etc/open5gs
    networks:
      - overlay-5g
      - overlay-radio
    deploy:
      placement:
        constraints:
          - node.hostname == vm-core-5g

  webui:
    image: gradiant/open5gs-webui:2.7.0
    environment:
      - DB_URI=mongodb://mongodb/open5gs
    networks:
      - overlay-5g
    ports:
      - "3000:3000"
    deploy:
      placement:
        constraints:
          - node.hostname == vm-core-5g

networks:
  overlay-5g:
    external: true
    name: overlay-5g
  overlay-radio:
    external: true
    name: overlay-radio

volumes:
  mongodb-data: