version: "3.8"

services:

  mongodb:
    image: mongo:6
    container_name: mongodb
    networks:
      overlay-5g:
        ipv4_address: 10.0.4.10
    volumes:
      - mongodb-data:/data/db

  open5gs:
    image: gradiant/open5gs:2.7.0
    container_name: open5gs
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    environment:
      - DB_URI=mongodb://10.0.4.10/open5gs
    networks:
      overlay-5g:
        ipv4_address: 10.0.4.2
      overlay-radio:
        ipv4_address: 10.0.6.2
    volumes:
      - ../../config/open5gs:/etc/open5gs
    depends_on:
      - mongodb

  webui:
    image: gradiant/open5gs-webui:2.7.0
    container_name: webui
    environment:
      - DB_URI=mongodb://10.0.4.10/open5gs
    networks:
      overlay-5g:
        ipv4_address: 10.0.4.5
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

networks:
  overlay-5g:
    external: true
    name: overlay-5g
  overlay-radio:
    external: true
    name: overlay-radio

volumes:
  mongodb-data:
