logger:
  file: /var/log/open5gs/smf.log

smf:
  sbi:
    server:
      - address: 10.0.4.2
        port: 7777
    client:
      nrf:
        - uri: http://10.0.4.2:7777

  pfcp:
    server:
      - address: 10.0.4.2
    client:
      upf:
        - address: 10.0.4.2

  gtpc:
    server:
      - address: 10.0.4.2

  gtpu:
    server:
      - address: 10.0.4.2

  metrics:
    server:
      - address: 10.0.4.2
        port: 9090

  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: internet

  dns:
    - 8.8.8.8
    - 8.8.4.4

  mtu: 1400

  freeDiameter: /etc/freeDiameter/smf.conf
