mcc: '999'
mnc: '70'
nci: '0x000000010'
idLength: 32
tac: 1

linkIp: 10.0.1.10
ngapIp: 10.0.1.10
gtpIp: 10.0.1.10

amfConfigs:
  - address: 10.0.1.6
    port: 38412

slices:
  - sst: 1

ignoreStreamIds: true
